services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\GameCoreBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/AppGameCoreBundle.php'
