services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\SystemBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/AppSystemBundle.php'
