services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\GameLogicBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/AppGameLogicBundle.php'
